Image comp
theVivek-kumar/KERNEL-UI pull request #3
Opened 2022-02-09 19:05 UTC by Vivek-jpg

image component done please review

2022-02-09 19:39 UTC, manojsarna approved these changes
Overall its looking good!!

Good to merge!!

2022-02-09 19:39 UTC, manojsarna commented on image-comp/image.html
> +            <div class="aside-body heading">
try to avoid using jpg or png , try using webp ( for web optimization). just a suggestion!!!

2022-02-09 19:39 UTC, manojsarna commented on image-comp/image.css
> +    margin: 1rem;
looks good!!

2022-02-09 19:41 UTC, pankaj-prog requested changes
- FIx the gap in the sidebar
- In the image demo, the images in the center will look great.

Other than this documentation bg color is great.

2022-02-09 19:41 UTC, pankaj-prog commented on image-comp/image.css
> +}
give border radius 50% instead of 40px to make it round

2022-02-10 05:00 UTC, nisargpawade reviewed
looking good, just not sure about the h2 headings which have extra space to their left.
you made class for h2 in styles.css but never used it

2022-02-10 15:04 UTC, nisargpawade approved these changes

2022-02-11 11:17 UTC, Vivek-jpg commented on image-comp/image.css
> +    margin: 1rem;
thanks

2022-02-11 11:40 UTC, merged